### ISSUE TITLE
kepub missing cover image

### ISSUE THREAD

**Issue by josephtannenbaum** [standardebooks/willa-cather_my-antonia#1]
When using the [kepub](https://standardebooks.org/ebooks/willa-cather/my-antonia) on a Kobo, the cover image doesn't show up on the books list or lock screen (just the first page with the title/author)

**Comment by acabal** [comment]
Hi there, make sure you're transferring to you ereader using a USB cable and a file manager, not a program like Calibre which will alter the ebook during the transfer. See our help page for more info: https://standardebooks.org/help/how-to-use-our-ebooks#transferring-to-your-ereader

**Comment by josephtannenbaum** [comment]
Thank you. I have only downloaded the kepub file directly using the Kobo browser (not the best method I'm sure) and it didn't have the cover while another book downloaded this way did. I'll try using a USB cable and update if that worked

**Comment by josephtannenbaum** [comment]
Hi!

I removed the kepub completely on the Kobo Clara HD using _Remove > Remove from My Books_, then followed the instructions in the link and the new copy still didn't have a cover. (Sorry if this is not the best place to report this. The book itself is really nice!)

Edit: Great news, transferring another Standard Ebook (In this case _The Secret Garden_) in the same way somehow fixed _My Ántonia_ 🤔 My guess is the device didn't feel the need to refresh book covers until it saw a totally new book...

**Comment by acabal** [comment]
Is your Kobo firmware up to date? Can you send the version number of the firmware?

**Comment by josephtannenbaum** [comment]
It has software version 4.15.12920 (which seems to be the latest.) I'll close though, I think it was a problem with the device and not this book. Thanks again
